import createError from "../utils/createError"

export const createReview = async(req,res,next) =>{
    try {
        
    } catch (error) {
        next(error)
    }
}


export const getReviews = async(req,res,next) =>{
    try {
        
    } catch (error) {
        next(error)
    }
}
export const deleteReview = async(req,res,next) =>{
    try {
        
    } catch (error) {
        next(error)
    }
}